# Generated by Django 6.0.2 on 2026-03-11 01:24

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=200)),
                ('date', models.DateTimeField()),
                ('city', models.TextField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=50)),
                ('category', models.CharField(choices=[('alumni', 'Alumni'), ('voltra_team', 'Voltra team'), ('city_team', 'City team'), ('department', 'Department')], max_length=20)),
                ('target_audience', models.CharField(max_length=200)),
                ('venue', models.BooleanField()),
                ('is_finished', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photo_id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('speaker_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EventUser',
            fields=[
                ('eventuser_id', models.AutoField(primary_key=True, serialize=False)),
                ('track', models.CharField(max_length=150)),
                ('is_checked', models.BooleanField(default=False)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
        ),
    ]
