# Generated by Django 6.0.2 on 2026-03-11 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventuser',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='photo',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_speakers',
            field=models.ManyToManyField(related_name='event_speakers', to='event.speaker'),
        ),
        migrations.AlterUniqueTogether(
            name='eventuser',
            unique_together={('event_id', 'user_id')},
        ),
    ]
