# Generated by Django 6.0.2 on 2026-03-11 01:24

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRequest',
            fields=[
                ('eventrequest_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('alumni', 'Alumni'), ('voltra_team', 'Voltra team'), ('city_team', 'City team'), ('department', 'Department')], max_length=20)),
                ('event_type', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=50)),
                ('objective', models.TextField()),
                ('target_audience', models.CharField(max_length=200)),
                ('expected_attendees', models.IntegerField()),
                ('event_date', models.DateTimeField()),
                ('city', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('new', 'New'), ('reviewing', 'Reviewing')], default='new', max_length=20)),
                ('venue', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_design', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('speaker', models.ManyToManyField(related_name='request_speakers', to='event.speaker')),
            ],
        ),
    ]
