# Generated by Django 6.0.3 on 2026-03-30 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_request', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventrequest',
            old_name='eveny_time',
            new_name='event_time',
        ),
    ]
