# Generated by Django 6.0.3 on 2026-03-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_request', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrequest',
            name='category',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], max_length=20),
        ),
    ]
